# Generated by Django 3.2.7 on 2021-09-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
