# Generated by Django 3.2.7 on 2021-09-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Other', 'Other')], default='Food', max_length=100),
        ),
    ]
